complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Za-z0-9]*'

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
  NewLineAtEndOfFile:
    active: false