name: ci

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level:
          - 21
          - 29

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          !~/.gradle/wrapper/dists/**/gradle*.zip
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build
      run: ./gradlew build --no-daemon

    - name: Run unit tests
      run: ./gradlew testBetaDebugUnitTest

    - name: Disable animations and transitions on Emulator
      run:
        adb shell settings put global window_animation_scale 0.0
        adb shell settings put global transition_animation_scale 0.0
        adb shell settings put global animator_duration_scale 0.0

    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        script: ./gradlew connectedBetaDebugAndroidTest

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: app/build/reports
      if: always()
